language: php
sudo: false

php:
  - 5.6
  - 7.0
  - hhvm

services:
  - rabbitmq

before_script:
  - composer install --dev

script:
  - phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
